# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#default-prompt-format
right_format = """
$time
"""

[time]
disabled = false
format = '[$time]($style) '
style="248"
time_format = '%T'
utc_time_offset = 'local'


# Disable git-status for now, it absolutely kills performance for the whole shell on myHDD.
[git_status]
disabled = true

[env_var.NODE_ENV]
variable = 'NODE_ENV'
format = '[NODE_ENV=$env_value]($style) '


# Custom
[bun]
format = '([$symbol($version )]($style))'
symbol = "Bun "
style = "bold 8"

[nodejs]
format = '([$symbol($version )]($style))'
version_format = 'v${major}'
symbol = "îœ˜ "

[python]
format = '([${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'
detect_folders = ['.venv', 'venv']
symbol = "îˆµ "

# Preset: No empty icons
[aws]
symbol = "îŒ½  "

[buf]
format = '(with [$symbol$version ]($style))'
symbol = "ï’ "

[c]
format = '([$symbol($version(-$name) )]($style))'
symbol = "î˜ "

[cmake]
format = '([$symbol($version )]($style))'

[cobol]
format = '([$symbol($version )]($style))'

[conda]
symbol = "ï„Œ "

[crystal]
format = '([$symbol($version )]($style))'
symbol = "î˜¯ "

[daml]
format = '([$symbol($version )]($style))'

[dart]
format = '([$symbol($version )]($style))'
symbol = "î˜ "

[directory]
read_only = " ó°Œ¾"

[docker_context]
symbol = "ïŒˆ "

[deno]
format = '([$symbol($version )]($style))'

[dotnet]
format = '([$symbol($version )(ğŸ¯ $tfm )]($style))'

[elixir]
format = '([$symbol($version \(OTP $otp_version\) )]($style))'
symbol = "î˜­ "

[elm]
format = '([$symbol($version )]($style))'
symbol = "î˜¬ "

[erlang]
format = '([$symbol($version )]($style))'

[fennel]
format = '([$symbol($version )]($style))'
symbol = "îš¯ "

[git_branch]
symbol = "ï˜ "

[golang]
format = '([$symbol($version )]($style))'
symbol = "î˜§ "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
format = '([$symbol($version )]($style))'
symbol = "î· "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[helm]
format = '([$symbol($version )]($style))'

[java]
format = '([$symbol($version )]($style))'
symbol = "î‰– "

[julia]
format = '([$symbol($version )]($style))'
symbol = "î˜¤ "

[kotlin]
format = '([$symbol($version )]($style))'
symbol = "î˜´ "

[lua]
format = '([$symbol($version )]($style))'
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[nim]
format = '([$symbol($version )]($style))'
symbol = "ó°†¥ "

[ocaml]
format = '([$symbol($version )(\($switch_indicator$switch_name\) )]($style))'
symbol = "î™º "

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[opa]
format = '([$symbo($version ]($style))"'

[package]
format = '(is [$symbol$version]($style) )'
symbol = "ó°— "

[perl]
format = '([$symbol($version )]($style))'
symbol = "î™¾ " 

[php]
format = '([$symbol($version )]($style))'
symbol = "î˜ˆ "

[purescript]
format = '([$symbol($version )]($style))'

[pijul_channel]
symbol = "ï˜ "

[raku]
format = '([$symbol($version-$vm_version )]($style))'

[red]
format = '([$symbol($version )]($style))'

[rlang]
format = '([$symbol($version )]($style))'
symbol = "ó°Ÿ” "

[ruby]
format = '([$symbol($version )]($style))'
symbol = "î‘ "

[rust]
format = '([$symbol($version )]($style))'
symbol = "î¨ "

[scala]
format = '([$symbol($version )]($style))'
symbol = "îœ· "

[swift]
format = '([$symbol($version )]($style))'
symbol = "î• "


[vagrant]
format = '([$symbol($version )]($style))'

[vlang]
format = '([$symbol($version )]($style))'

[zig]
format = '([$symbol($version )]($style))'
symbol = "îš© "